spring:
  thymeleaf:
    # if false, helps to develop view without restart of app
    cache: true
  datasource:
    generate-unique-name: false
    name: tacocloud
  jpa:
    show-sql: true

logging:
  level:
    org:
      springframework:
        jdbc:
          core: DEBUG