spring:
  thymeleaf:
    # if false, helps to develop view without restart of app
    cache: true
#  data:
#    mongodb:
#      database: tacoclouddb
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 320532025645-b0tqf0c6j200kkb3uf5ho1bne7pfveip.apps.googleusercontent.com
            client-secret: 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
            client-name: taco-client
            redirect-uri: http://localhost:8080/login/oauth2/code/google
            scope:
              - email
              - profile
  datasource:
    generate-unique-name: false
    username: user
    password: password
    url: jdbc:postgresql://localhost:5432/tacocloud
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQL9Dialect

logging:
  level:
    org:
      springframework:
        jdbc:
          core: DEBUG